version: '3'

services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles